In [2]:
df.describe()

,Compactness,SurfaceArea,WallArea,RoofArea,Height,GlazingLevel,HeatingLoad,CoolingLoad
count,768.000000,768.000000,768.000000,767.000000,768.00000,768.000000,768.000000,768.000000
mean,0.764167,671.708333,318.500000,176.387223,5.25000,0.234375,22.307201,24.587760
std,0.105777,88.086116,43.626481,45.573664,1.75114,0.133221,10.090196,9.513306
min,0.620000,514.500000,245.000000,0.000000,3.50000,0.000000,6.010000,10.900000
25%,0.682500,606.375000,294.000000,134.750000,3.50000,0.100000,12.992500,15.620000
50%,0.750000,673.750000,318.500000,147.000000,5.25000,0.250000,18.950000,22.080000
75%,0.830000,741.125000,343.000000,220.500000,7.00000,0.400000,31.667500,33.132500
max,0.980000,808.500000,416.500000,220.500000,7.00000,0.400000,43.100000,48.030000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Compactness              768 non-null    float64
 1   SurfaceArea              768 non-null    float64
 2   WallArea                 768 non-null    float64
 3   RoofArea                 767 non-null    float64
 4   Height                   768 non-null    float64
 5   Orientation              768 non-null    object
 6   GlazingLevel             768 non-null    float64
 7   GlazingAreaDistribution  768 non-null    object
 8   HeatingLoad              768 non-null    float64
 9   CoolingLoad              768 non-null    float64
dtypes: float64(8), object(2)
memory usage: 60.1+ KB

In [4]:
df.tail()

,Compactness,SurfaceArea,WallArea,RoofArea,Height,Orientation,GlazingLevel,GlazingAreaDistribution,HeatingLoad,CoolingLoad
763,0.64,784.0,343.0,220.5,3.5,West,0.4,West,17.88,21.40
764,0.62,808.5,367.5,220.5,3.5,North,0.4,West,16.54,16.88
765,0.62,808.5,367.5,220.5,3.5,East,0.4,West,16.44,17.11
766,0.62,808.5,367.5,220.5,3.5,South,0.4,West,16.48,16.61
767,0.62,808.5,367.5,220.5,3.5,West,0.4,West,16.64,16.03

In [5]:
df.head()

,Compactness,SurfaceArea,WallArea,RoofArea,Height,Orientation,GlazingLevel,GlazingAreaDistribution,HeatingLoad,CoolingLoad
0,0.98,514.5,294.0,110.25,7.0,North,0.0,None,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,East,0.0,None,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,South,0.0,None,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,West,0.0,None,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,North,0.0,None,20.84,28.28

In [6]:
print("Mean:")
print(df.mean(numeric_only=True))
print("\nMedian:")
print(df.median(numeric_only=True))
print("\nMode:")
print(df.mode())
print("\nStandard deviation:")
print(df.std(numeric_only=True))
print("\nVariance:")
print(df.var(numeric_only=True))
print("\nRange:")
print(df.max(numeric_only=True)-df.min(numeric_only=True))

Mean:
Compactness       0.764167
SurfaceArea     671.708333
WallArea        318.500000
RoofArea        176.387223
Height            5.250000
GlazingLevel      0.234375
HeatingLoad      22.307201
CoolingLoad      24.587760
dtype: float64

Median:
Compactness       0.75
SurfaceArea     673.75
WallArea        318.50
RoofArea        147.00
Height            5.25
GlazingLevel      0.25
HeatingLoad      18.95
CoolingLoad      22.08
dtype: float64

Mode:
    Compactness  SurfaceArea  WallArea  RoofArea  Height Orientation  \
0          0.62        514.5     294.0     220.5     3.5        East
1          0.64        563.5     318.5       NaN     7.0       North
2          0.66        588.0       NaN       NaN     NaN       South
3          0.69        612.5       NaN       NaN     NaN        West
4          0.71        637.0       NaN       NaN     NaN         NaN
5          0.74        661.5       NaN       NaN     NaN         NaN
6          0.76        686.0       NaN       NaN     NaN         NaN
7          0.79        710.5       NaN       NaN     NaN         NaN
8          0.82        735.0       NaN       NaN     NaN         NaN
9          0.86        759.5       NaN       NaN     NaN         NaN
10         0.90        784.0       NaN       NaN     NaN         NaN
11         0.98        808.5       NaN       NaN     NaN         NaN

    GlazingLevel GlazingAreaDistribution  HeatingLoad  CoolingLoad
0           0.10                    East        15.16        14.27
1           0.25                   North          NaN        14.28
2           0.40                   South          NaN        17.20
3            NaN                 Uniform          NaN        21.33
4            NaN                    West          NaN        29.79
5            NaN                     NaN          NaN          NaN
6            NaN                     NaN          NaN          NaN
7            NaN                     NaN          NaN          NaN
8            NaN                     NaN          NaN          NaN
9            NaN                     NaN          NaN          NaN
10           NaN                     NaN          NaN          NaN
11           NaN                     NaN          NaN          NaN

Standard deviation:
Compactness      0.105777
SurfaceArea     88.086116
WallArea        43.626481
RoofArea        45.573664
Height           1.751140
GlazingLevel     0.133221
HeatingLoad     10.090196
CoolingLoad      9.513306
dtype: float64

Variance:
Compactness        0.011189
SurfaceArea     7759.163842
WallArea        1903.269883
RoofArea        2076.958870
Height             3.066493
GlazingLevel       0.017748
HeatingLoad      101.812050
CoolingLoad       90.502983
dtype: float64

Range:
Compactness       0.36
SurfaceArea     294.00
WallArea        171.50
RoofArea        220.50
Height            3.50
GlazingLevel      0.40
HeatingLoad      37.09
CoolingLoad      37.13
dtype: float64

In [8]:
df['Orientation'].value_counts()

North    192
East     192
South    192
West     192
Name: Orientation, dtype: int64

In [9]:
df['GlazingAreaDistribution'].value_counts()

Uniform    144
North      144
East       144
South      144
West       144
None        48
Name: GlazingAreaDistribution, dtype: int64